### ISSUE TITLE
0.模型参数单位书写规范

### ISSUE THREAD

**Issue by crazyzlj** [seims/SEIMS#41]
##  模型参数单位书写规范

大家在读源代码时候，遇到参数单位，需要检查一下是否符合以下规范（要转换为国标单位，避免使用ha之类），如果不符合，应改为一致，这个列表应该不断增加：

> 参数单位的定义主要是在模块`api.cpp`文件中定义，相关宏定义`#define UNITS_NAME "string"`应在`src\base\util\text.h` 中不断增加，完善！宏定义规范为`UNIT_<name abbr.>_<unit abbr.>`

变量名|单位|中文单位名|宏定义名
---|---|---|---
无量纲|""|空|UNIT_NON_DIM
温度|deg C|摄氏度|UNIT_TEMP_DEG
经纬度|degree|度|UNIT_LONLAT_DEG
长度|m|米|UNIT_LEN_M
面积|km2|平方千米|UNIT_AREA_KM2
污染物含量|kg/km2|千克每平方千米|UNIT_CONT_KGKM2
流量|m3/s|立方米每秒|UNIT_FLOW_CMS
水量变化|mm/d|毫米每天|UNIT_WTRDLT_MMD

**Comment by seims** [comment]
# 模型中变量命名及定义、赋值规范
================
+ 模块用到的变量、参数需要在api.cpp中以AddParameter或AddInput定义，输出变量用AddOutput定义
+ 这些变量需要在模块头文件(.h)中进行相应的定义
+ 随后在实现文件(.cpp)中，SetValue系列或GetValue系列函数中，均需要有相应的赋值语句。

一些约定俗成的变量定义：

+ 有效栅格数（去除NoDATA），DT_Single，api.cpp中变量名为Tag_CellSize，头文件中定义为

```cpp
//! Valid cells number
int m_nCells;
```

+ 栅格宽度（m），DT_Single，api.cpp中变量名为Tag_CellWidth，头文件中定义为

```cpp
//! Grid length (m)
float m_CellWidth;
```
